repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--config=.config/black.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--config=ruff.toml]
        exclude: ^(results/|data_analysis/|main_run_data_analysis\.py|preprocess_trajectories\.py)
      - id: ruff-format
        args: [--config=ruff.toml]
        exclude: ^(results/|data_analysis/|main_run_data_analysis\.py|preprocess_trajectories\.py)