agent:
  step_limit: 30
  cost_limit: 2.
  total_timeout: 3600

environment:
  docker_image_name: yarinamomo/kaggle_python_env
  problem_mode: JunoBench_Buggy
  target_nb_instance: sklearn_1
  source_path_parent: example/test_case/
  run_all_instances: false
  docker_mount_path: example/docker_mount/
  docker_start_command: "jupyter server --allow-root --ServerApp.ip=0.0.0.0 --ServerApp.port=8888 --ServerApp.token='' --ServerApp.password='' --ServerApp.open_browser=False"
  timeout: 1800

models:
  - model_name: glm-4.7-355b
    cost_tracking: ignore_errors
    model_kwargs:
      custom_llm_provider: openai
      api_base: https://aqueduct.ai.datalab.tuwien.ac.at/v1
      input_cost_per_token: 0.00000027778
      output_cost_per_token: 0.00000111111

misc:
  mode: agent
  run_count: 3
  if_local_key: true
  skip_existing: true
  enable_summary_log: true
